export const INDIAN_STATES = [
  "Andaman and Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];

export const FAQ_DATA = [
  {
    question: "What are carbon credits?",
    answer: "Carbon credits are measurable, verifiable permits that allow the owner to emit one tonne of CO2 or an equivalent amount of another greenhouse gas. Farmers can earn these credits by adopting practices that capture and store carbon in their soil and vegetation, like reforestation or regenerative agriculture. These credits can then be sold to companies to offset their emissions.",
  },
  {
    question: "Is this really free?",
    answer: "Yes, our preliminary analysis is completely free. We provide an AI-powered estimate to help you understand your farmland's potential without any upfront cost or commitment. This allows you to explore your options before investing in expensive, official verification processes.",
  },
  {
    question: "How accurate is the estimate?",
    answer: "Our AI analysis provides a high-quality preliminary estimate based on satellite imagery and, if provided, local climate data. While it's a powerful tool for initial assessment, it is not a substitute for a formal, on-the-ground survey by a certified body. The final verified carbon credit amount may vary.",
  },
  {
    question: "What do I need to get started?",
    answer: "All you need is a clear, recent photo of your farmland. For a more accurate analysis, we recommend providing your farm's city and state. This allows our AI to factor in local climate conditions, which can significantly impact carbon sequestration potential.",
  },
  {
    question: "What happens after the analysis?",
    answer: "Our report provides an estimate and a list of next steps. This includes guidance on finding certified carbon programs (like Verra or the Indian government's CAMPA), getting a professional land survey, and understanding the long-term commitments involved. Our expert chatbot can also answer any further questions you may have.",
  },
];
